/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jmonkeyengine;

import com.jme3.app.SimpleApplication;
import com.jme3.app.state.AppState;
import com.jme3.app.state.VideoRecorderAppState;

public class App extends SimpleApplication {

    public App(AppState... initialStates){
        super(initialStates);
    }

    @Override
    public void simpleInitApp(){
        setTimer(new VideoRecorderAppState.IsoTimer(60));
    }

}