name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create reports directory
      run: |
        mkdir -p build/reports
    - name: Set Mesa3D log file
      run: |
        echo "MESA_DEBUG=flush" >> $GITHUB_ENV
        echo "MESA_LOG_FILE=build/reports/mesa3d.log" >> $GITHUB_ENV
    - name: Install Mesa3D
      run: |
        sudo apt-get update
        sudo apt-get install -y mesa-utils libgl1-mesa-dri libgl1-mesa-glx xvfb x11-utils

    - name: Set environment variables for Mesa3D
      run: |
        echo "LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV
        echo "MESA_LOADER_DRIVER_OVERRIDE=llvmpipe" >> $GITHUB_ENV
    - name: Start xvfb
      run: |
        sudo Xvfb :99 -ac -screen 0 1024x768x24 > build/reports/xvfb.log 2>&1 &
        export DISPLAY=:99
        echo "DISPLAY=:99" >> $GITHUB_ENV
        sleep 3  # Give xvfb some time to start
    - name: Verify xvfb
      run: xdpyinfo -display :99
    - name: Verify Mesa3D Installation
      run: |
        glxinfo | grep "OpenGL"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        name: test-results
        path: '**/build/test-results/**'
    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        name: test-reports
        path: '**/build/reports/**'
    - name: Upload Changed Image
      uses: actions/upload-artifact@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        name: changed-images
        path: '**/build/changed-images/**'
    - name: Upload error logs
      if: always()  # Ensures this step runs even if previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: hs_err_logs
        path: /home/runner/work/jmonkeyengine/jmonkeyengine/jme3-screenshot-tests/hs_err_pid*.log